import type { BudgetLevel, Deal, Destination, Route, TransportType } from '../../types';

export type TravelProfile =
  | 'hill_station'
  | 'beach'
  | 'heritage_city'
  | 'backwaters'
  | 'pilgrimage'
  | 'wildlife'
  | 'desert'
  | 'northeast'
  | 'metro_escape';

export type TravelZone = 'north' | 'west' | 'south' | 'east' | 'central' | 'northeast';

export interface LaunchDestination extends Destination {
  travelProfile: TravelProfile;
  zone: TravelZone;
  nearestRailHub: string;
  nearestAirport: string;
  bestMonths: string[];
  avoidMonths: string[];
  budgetHighlights: string[];
  localTransportNote: string;
  sampleBudgetPerDay: number;
  sampleMidBudgetPerDay: number;
  tags: string[];
  planningScore: number;
}

const destinationImageBase = 'https://images.unsplash.com/';

export const launchDestinations: LaunchDestination[] = [
  {
    id: 'manali',
    name: 'Manali',
    region: 'Himachal Pradesh',
    country: 'India',
    baseCostIndex: 0.85,
    description: 'Popular Himalayan budget base with hostels, Volvo buses from Delhi, and easy access to Solang and Old Manali.',
    avgHotelPrice: 1700,
    imageUrl: `${destinationImageBase}photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'hill_station',
    zone: 'north',
    nearestRailHub: 'Chandigarh',
    nearestAirport: 'Kullu–Manali',
    bestMonths: ['March', 'April', 'May', 'September', 'October'],
    avoidMonths: ['July', 'August'],
    budgetHighlights: ['Volvo buses from Delhi are usually the best value.', 'Old Manali and Vashisht have deeper budget inventory than luxury resorts.'],
    localTransportNote: 'Autos are limited; budget travelers usually rely on shared cabs, scooters, or short local bus hops.',
    sampleBudgetPerDay: 1800,
    sampleMidBudgetPerDay: 3200,
    tags: ['mountains', 'cool-weather', 'hostels'],
    planningScore: 4.7,
  },
  {
    id: 'dharamshala',
    name: 'Dharamshala',
    region: 'Himachal Pradesh',
    country: 'India',
    baseCostIndex: 0.82,
    description: 'Good-value mountain break with budget stays in McLeod Ganj, strong café scene, and easy bus access from North India.',
    avgHotelPrice: 1600,
    imageUrl: `${destinationImageBase}photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'hill_station',
    zone: 'north',
    nearestRailHub: 'Pathankot',
    nearestAirport: 'Kangra',
    bestMonths: ['March', 'April', 'May', 'September', 'October', 'November'],
    avoidMonths: ['July', 'August'],
    budgetHighlights: ['McLeod Ganj hostels keep solo budgets low.', 'Pathankot train plus bus combo is usually cheaper than flying.'],
    localTransportNote: 'Short taxi hops add up on steep roads, so choose a stay near your main market area.',
    sampleBudgetPerDay: 1700,
    sampleMidBudgetPerDay: 3000,
    tags: ['mountains', 'monasteries', 'cafes'],
    planningScore: 4.6,
  },
  {
    id: 'rishikesh',
    name: 'Rishikesh',
    region: 'Uttarakhand',
    country: 'India',
    baseCostIndex: 0.78,
    description: 'Affordable river town with a broad stay range, yoga hostels, and direct bus and rail access via Haridwar and Dehradun.',
    avgHotelPrice: 1500,
    imageUrl: `${destinationImageBase}photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'metro_escape',
    zone: 'north',
    nearestRailHub: 'Haridwar',
    nearestAirport: 'Dehradun',
    bestMonths: ['February', 'March', 'April', 'September', 'October', 'November'],
    avoidMonths: ['July', 'August'],
    budgetHighlights: ['Laxman Jhula side has the highest density of backpacker stays.', 'Local cafés and ashram meals make daily spend easy to control.'],
    localTransportNote: 'Most short routes are walkable or can be covered by shared auto and scooter rental.',
    sampleBudgetPerDay: 1600,
    sampleMidBudgetPerDay: 2800,
    tags: ['wellness', 'riverfront', 'weekend'],
    planningScore: 4.5,
  },
  {
    id: 'jaipur',
    name: 'Jaipur',
    region: 'Rajasthan',
    country: 'India',
    baseCostIndex: 0.95,
    description: 'Strong first-time India city break with dense hotel supply, rail access, and many paid attractions concentrated near the old city.',
    avgHotelPrice: 2100,
    imageUrl: `${destinationImageBase}photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'heritage_city',
    zone: 'north',
    nearestRailHub: 'Jaipur Junction',
    nearestAirport: 'Jaipur',
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    avoidMonths: ['May', 'June'],
    budgetHighlights: ['Train travel keeps Jaipur one of the easiest value breaks from Delhi.', 'Bani Park and MI Road usually give a better stay-price balance than tourist-heavy core areas.'],
    localTransportNote: 'Autos and app cabs are easy, but fort circuits are cheaper if grouped into one day.',
    sampleBudgetPerDay: 2100,
    sampleMidBudgetPerDay: 3600,
    tags: ['heritage', 'markets', 'forts'],
    planningScore: 4.7,
  },
  {
    id: 'jodhpur',
    name: 'Jodhpur',
    region: 'Rajasthan',
    country: 'India',
    baseCostIndex: 0.9,
    description: 'Budget-friendly blue city with good rail links, heritage guesthouses, and a compact core for low local transport spend.',
    avgHotelPrice: 1900,
    imageUrl: `${destinationImageBase}photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'heritage_city',
    zone: 'north',
    nearestRailHub: 'Jodhpur Junction',
    nearestAirport: 'Jodhpur',
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    avoidMonths: ['May', 'June'],
    budgetHighlights: ['Guesthouses near the old city remain strong value outside holiday spikes.', 'Sleeper rail works well for budget overnights from Jaipur or Delhi.'],
    localTransportNote: 'Most old-city sightseeing is walkable; reserve autos for fort and outlying points.',
    sampleBudgetPerDay: 1900,
    sampleMidBudgetPerDay: 3300,
    tags: ['heritage', 'desert-edge', 'architecture'],
    planningScore: 4.5,
  },
  {
    id: 'udaipur',
    name: 'Udaipur',
    region: 'Rajasthan',
    country: 'India',
    baseCostIndex: 1.08,
    description: 'Lake city with romantic appeal but enough guesthouses and sleeper buses to still work for budget-conscious travelers.',
    avgHotelPrice: 2400,
    imageUrl: `${destinationImageBase}photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'heritage_city',
    zone: 'north',
    nearestRailHub: 'Udaipur City',
    nearestAirport: 'Maharana Pratap',
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    avoidMonths: ['May', 'June'],
    budgetHighlights: ['Guesthouses outside the main lakefront are much cheaper with only a small convenience hit.', 'Night buses can be better value than flights from nearby metros.'],
    localTransportNote: 'Local autos are common; keep one day for clustered old-city walking to contain costs.',
    sampleBudgetPerDay: 2200,
    sampleMidBudgetPerDay: 3900,
    tags: ['lakes', 'heritage', 'couples'],
    planningScore: 4.6,
  },
  {
    id: 'jaisalmer',
    name: 'Jaisalmer',
    region: 'Rajasthan',
    country: 'India',
    baseCostIndex: 1.02,
    description: 'Desert destination with low room rates off peak, but camel safari and camp packages can swing the final budget sharply.',
    avgHotelPrice: 2100,
    imageUrl: `${destinationImageBase}photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'desert',
    zone: 'north',
    nearestRailHub: 'Jaisalmer',
    nearestAirport: 'Jaisalmer',
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    avoidMonths: ['May', 'June', 'July'],
    budgetHighlights: ['Fort-side guesthouses stay reasonable outside the December holiday window.', 'Desert camp bundles need scrutiny because activities often hide the true trip cost.'],
    localTransportNote: 'Old town is walkable; desert excursions are best booked as shared departures to avoid private jeep costs.',
    sampleBudgetPerDay: 2100,
    sampleMidBudgetPerDay: 3700,
    tags: ['desert', 'fort', 'safari'],
    planningScore: 4.4,
  },
  {
    id: 'goa',
    name: 'Goa',
    region: 'West Coast',
    country: 'India',
    baseCostIndex: 1.18,
    description: 'Still workable on a budget if timed outside December peaks and split between train arrival and scooter-based local movement.',
    avgHotelPrice: 2600,
    imageUrl: `${destinationImageBase}photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'beach',
    zone: 'west',
    nearestRailHub: 'Madgaon',
    nearestAirport: 'Goa Mopa / Dabolim',
    bestMonths: ['November', 'January', 'February'],
    avoidMonths: ['December', 'June', 'July', 'August'],
    budgetHighlights: ['South Goa usually gives better room value than peak North Goa strips.', 'Train plus scooter rental beats short-notice flights for budget travelers.'],
    localTransportNote: 'Scooter rental is the key cost-control lever because taxi pricing is punitive on beach circuits.',
    sampleBudgetPerDay: 2500,
    sampleMidBudgetPerDay: 4300,
    tags: ['beaches', 'nightlife', 'scooter'],
    planningScore: 4.6,
  },
  {
    id: 'gokarna',
    name: 'Gokarna',
    region: 'Karnataka Coast',
    country: 'India',
    baseCostIndex: 0.88,
    description: 'Cheaper beach alternative to Goa with simpler stay stock, slower vibe, and good value in guesthouses and homestays.',
    avgHotelPrice: 1800,
    imageUrl: `${destinationImageBase}photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'beach',
    zone: 'south',
    nearestRailHub: 'Gokarna Road',
    nearestAirport: 'Goa Dabolim',
    bestMonths: ['November', 'December', 'January', 'February'],
    avoidMonths: ['June', 'July', 'August'],
    budgetHighlights: ['Guesthouses near Kudle and Gokarna town are better value than isolated resort pockets.', 'Rail arrival plus local auto is usually the cheapest access path.'],
    localTransportNote: 'Short auto rides and walking work best; beach-hopping by taxi gets expensive quickly.',
    sampleBudgetPerDay: 1800,
    sampleMidBudgetPerDay: 3200,
    tags: ['beaches', 'backpacker', 'quiet'],
    planningScore: 4.5,
  },
  {
    id: 'munnar',
    name: 'Munnar',
    region: 'Kerala',
    country: 'India',
    baseCostIndex: 1.05,
    description: 'Scenic tea-hill destination where room rates are manageable but last-mile transfers can meaningfully change the total budget.',
    avgHotelPrice: 2400,
    imageUrl: `${destinationImageBase}photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'hill_station',
    zone: 'south',
    nearestRailHub: 'Aluva',
    nearestAirport: 'Kochi',
    bestMonths: ['September', 'October', 'November', 'December', 'January', 'February'],
    avoidMonths: ['June', 'July'],
    budgetHighlights: ['Munnar is cheaper when paired with bus transfers instead of private cabs from Kochi.', 'Town-center stays are better value than isolated plantation resorts.'],
    localTransportNote: 'Local sightseeing often requires shared jeep, bus, or a negotiated cab day; factor that in early.',
    sampleBudgetPerDay: 2200,
    sampleMidBudgetPerDay: 3800,
    tags: ['tea-estates', 'hills', 'scenic'],
    planningScore: 4.6,
  },
  {
    id: 'alleppey',
    name: 'Alleppey',
    region: 'Kerala',
    country: 'India',
    baseCostIndex: 1.0,
    description: 'Backwater trip where homestays can keep the budget modest if you avoid premium overnight houseboats.',
    avgHotelPrice: 2200,
    imageUrl: `${destinationImageBase}photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'backwaters',
    zone: 'south',
    nearestRailHub: 'Alappuzha',
    nearestAirport: 'Kochi',
    bestMonths: ['September', 'October', 'November', 'December', 'January', 'February'],
    avoidMonths: ['June', 'July'],
    budgetHighlights: ['Day cruises or shared boats give much better value than overnight luxury houseboats.', 'Town homestays keep the backwaters affordable.'],
    localTransportNote: 'Auto plus ferry is usually enough; avoid relying on frequent private transfers between canalside properties.',
    sampleBudgetPerDay: 2100,
    sampleMidBudgetPerDay: 3600,
    tags: ['backwaters', 'slow-travel', 'homestays'],
    planningScore: 4.4,
  },
  {
    id: 'varkala',
    name: 'Varkala',
    region: 'Kerala',
    country: 'India',
    baseCostIndex: 1.03,
    description: 'Cliffside beach town with a healthier budget profile than Goa when booked outside holiday spikes.',
    avgHotelPrice: 2300,
    imageUrl: `${destinationImageBase}photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'beach',
    zone: 'south',
    nearestRailHub: 'Varkala Sivagiri',
    nearestAirport: 'Thiruvananthapuram',
    bestMonths: ['November', 'December', 'January', 'February'],
    avoidMonths: ['June', 'July', 'August'],
    budgetHighlights: ['Rail access makes Varkala easier to do cheaply than many fly-in beach towns.', 'Stay a short walk off the cliff to cut nightly rates.'],
    localTransportNote: 'Most of the main beach zone is walkable; autos are mostly for station and day-trip transfers.',
    sampleBudgetPerDay: 2100,
    sampleMidBudgetPerDay: 3500,
    tags: ['beach', 'cliffs', 'wellness'],
    planningScore: 4.5,
  },
  {
    id: 'hampi',
    name: 'Hampi',
    region: 'Karnataka',
    country: 'India',
    baseCostIndex: 0.8,
    description: 'Excellent value heritage trip with guesthouses, bike rentals, and a strong backpacker infrastructure.',
    avgHotelPrice: 1500,
    imageUrl: `${destinationImageBase}photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'heritage_city',
    zone: 'south',
    nearestRailHub: 'Hospet',
    nearestAirport: 'Hubli',
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    avoidMonths: ['April', 'May'],
    budgetHighlights: ['Hospet train access and bike rentals make Hampi unusually budget-efficient.', 'Guesthouses near Virupapur Gaddi often stretch budgets further.'],
    localTransportNote: 'Scooter rental is the standard way to keep sightseeing costs low across temple clusters.',
    sampleBudgetPerDay: 1600,
    sampleMidBudgetPerDay: 2800,
    tags: ['ruins', 'backpacker', 'cycling'],
    planningScore: 4.7,
  },
  {
    id: 'mysuru',
    name: 'Mysuru',
    region: 'Karnataka',
    country: 'India',
    baseCostIndex: 0.86,
    description: 'Clean and easy heritage city break with inexpensive rail access from Bengaluru and a manageable local transit profile.',
    avgHotelPrice: 1700,
    imageUrl: `${destinationImageBase}photo-1583396618422-3b9f1efc9c35?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'heritage_city',
    zone: 'south',
    nearestRailHub: 'Mysuru Junction',
    nearestAirport: 'Mysuru',
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    avoidMonths: ['April', 'May'],
    budgetHighlights: ['Short rail hops from Bengaluru make Mysuru one of the best-value urban escapes in the south.', 'A two-night stay usually covers core sights without overpaying for transport.'],
    localTransportNote: 'Autos and buses are easy; most costs come from palace and day-trip coverage rather than city movement itself.',
    sampleBudgetPerDay: 1700,
    sampleMidBudgetPerDay: 3000,
    tags: ['heritage', 'weekend', 'palace'],
    planningScore: 4.4,
  },
  {
    id: 'ooty',
    name: 'Ooty',
    region: 'Tamil Nadu',
    country: 'India',
    baseCostIndex: 1.02,
    description: 'Classic hill station where train nostalgia and cool weather keep demand high, but off-center stays still preserve value.',
    avgHotelPrice: 2300,
    imageUrl: `${destinationImageBase}photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'hill_station',
    zone: 'south',
    nearestRailHub: 'Mettupalayam',
    nearestAirport: 'Coimbatore',
    bestMonths: ['March', 'April', 'May', 'September', 'October'],
    avoidMonths: ['July', 'August'],
    budgetHighlights: ['Mettupalayam rail or bus plus local cab beats direct private taxi on total cost.', 'Peak summer weekends inflate room rates sharply.'],
    localTransportNote: 'Shared vans and local buses help; private sightseeing cabs are the biggest cost trap here.',
    sampleBudgetPerDay: 2200,
    sampleMidBudgetPerDay: 3700,
    tags: ['hill-station', 'cool-weather', 'toy-train'],
    planningScore: 4.3,
  },
  {
    id: 'pondicherry',
    name: 'Pondicherry',
    region: 'Tamil Nadu Coast',
    country: 'India',
    baseCostIndex: 1.0,
    description: 'Strong short-break destination with walkable quarters, broad stay supply, and direct bus access from Chennai and Bengaluru.',
    avgHotelPrice: 2200,
    imageUrl: `${destinationImageBase}photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'beach',
    zone: 'south',
    nearestRailHub: 'Villupuram',
    nearestAirport: 'Chennai',
    bestMonths: ['November', 'December', 'January', 'February'],
    avoidMonths: ['October'],
    budgetHighlights: ['Guesthouses outside the French Quarter cut costs fast without hurting the experience.', 'Direct buses from Chennai are usually the budget winner.'],
    localTransportNote: 'Most core areas are cycle- and walk-friendly; local transport spend should be low if you stay central.',
    sampleBudgetPerDay: 2100,
    sampleMidBudgetPerDay: 3500,
    tags: ['coastal', 'cafes', 'weekend'],
    planningScore: 4.5,
  },
  {
    id: 'varanasi',
    name: 'Varanasi',
    region: 'Uttar Pradesh',
    country: 'India',
    baseCostIndex: 0.72,
    description: 'One of the easiest ultra-budget cultural trips in India if you keep the stay close to the ghats and lean on train arrivals.',
    avgHotelPrice: 1300,
    imageUrl: `${destinationImageBase}photo-1561361058-c24cecae35ca?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'pilgrimage',
    zone: 'north',
    nearestRailHub: 'Varanasi Junction',
    nearestAirport: 'Varanasi',
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    avoidMonths: ['May', 'June', 'July'],
    budgetHighlights: ['Few destinations match Varanasi on low accommodation spend.', 'Boats and guided experiences are where budgets usually creep.'],
    localTransportNote: 'Ghats are best explored on foot; use e-rickshaw or auto only for station and farther temples.',
    sampleBudgetPerDay: 1500,
    sampleMidBudgetPerDay: 2600,
    tags: ['spiritual', 'culture', 'ghats'],
    planningScore: 4.6,
  },
  {
    id: 'amritsar',
    name: 'Amritsar',
    region: 'Punjab',
    country: 'India',
    baseCostIndex: 0.82,
    description: 'Highly accessible city break with cheap rail links, wide hotel supply, and a compact sightseeing cluster around the Golden Temple.',
    avgHotelPrice: 1700,
    imageUrl: `${destinationImageBase}photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'pilgrimage',
    zone: 'north',
    nearestRailHub: 'Amritsar Junction',
    nearestAirport: 'Amritsar',
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March'],
    avoidMonths: ['May', 'June'],
    budgetHighlights: ['Langar and central budget hotels make daily costs easier than most urban breaks.', 'Rail arrival from Delhi is a strong price-performance option.'],
    localTransportNote: 'Core sights are close enough for low auto spend; Wagah transfer is the main extra transport cost.',
    sampleBudgetPerDay: 1700,
    sampleMidBudgetPerDay: 2900,
    tags: ['spiritual', 'food', 'weekend'],
    planningScore: 4.5,
  },
  {
    id: 'ranthambore',
    name: 'Ranthambore',
    region: 'Rajasthan',
    country: 'India',
    baseCostIndex: 1.16,
    description: 'Wildlife trip with manageable room rates but expensive safari slots, so timing and package selection matter more than hotel class.',
    avgHotelPrice: 2600,
    imageUrl: `${destinationImageBase}photo-1549366021-9f761d040a94?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'wildlife',
    zone: 'north',
    nearestRailHub: 'Sawai Madhopur',
    nearestAirport: 'Jaipur',
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March'],
    avoidMonths: ['July', 'August', 'September'],
    budgetHighlights: ['Safari permits, not rooms, are the main budget variable.', 'Stay near Sawai Madhopur station to avoid resort transfer premiums.'],
    localTransportNote: 'Shared safari gypsy or canter is the budget-conscious choice; private arrangements cost far more.',
    sampleBudgetPerDay: 2600,
    sampleMidBudgetPerDay: 4600,
    tags: ['wildlife', 'tiger', 'safari'],
    planningScore: 4.4,
  },
  {
    id: 'kaziranga',
    name: 'Kaziranga',
    region: 'Assam',
    country: 'India',
    baseCostIndex: 1.14,
    description: 'Wildlife destination with stronger value when paired with Guwahati-based access planning and shared park transfers.',
    avgHotelPrice: 2500,
    imageUrl: `${destinationImageBase}photo-1511497584788-876760111969?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'wildlife',
    zone: 'northeast',
    nearestRailHub: 'Furkating',
    nearestAirport: 'Jorhat / Guwahati',
    bestMonths: ['November', 'December', 'January', 'February', 'March', 'April'],
    avoidMonths: ['May', 'June', 'July', 'August'],
    budgetHighlights: ['Shared cab planning from Guwahati keeps access costs under control.', 'Park stays book up early in peak wildlife season.'],
    localTransportNote: 'Expect hired jeep legs around the park zone; this is not a destination where local public transport covers everything.',
    sampleBudgetPerDay: 2600,
    sampleMidBudgetPerDay: 4500,
    tags: ['wildlife', 'northeast', 'nature'],
    planningScore: 4.3,
  },
  {
    id: 'gangtok',
    name: 'Gangtok',
    region: 'Sikkim',
    country: 'India',
    baseCostIndex: 1.04,
    description: 'Mountain capital with decent hotel value, but permits and shared transfer logistics matter for realistic trip planning.',
    avgHotelPrice: 2300,
    imageUrl: `${destinationImageBase}photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'northeast',
    zone: 'northeast',
    nearestRailHub: 'New Jalpaiguri',
    nearestAirport: 'Bagdogra / Pakyong',
    bestMonths: ['March', 'April', 'May', 'October', 'November'],
    avoidMonths: ['July', 'August'],
    budgetHighlights: ['NJP plus shared jeep is usually the smartest arrival pattern.', 'MG Marg-adjacent stays reduce local taxi dependence.'],
    localTransportNote: 'Shared jeeps are the budget backbone for long scenic routes; private cars spike costs quickly.',
    sampleBudgetPerDay: 2300,
    sampleMidBudgetPerDay: 3900,
    tags: ['mountains', 'northeast', 'permits'],
    planningScore: 4.5,
  },
  {
    id: 'darjeeling',
    name: 'Darjeeling',
    region: 'West Bengal',
    country: 'India',
    baseCostIndex: 0.94,
    description: 'Classic hill town with rail nostalgia, broad mid-budget stay supply, and strong value when paired with NJP access.',
    avgHotelPrice: 2100,
    imageUrl: `${destinationImageBase}photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'hill_station',
    zone: 'east',
    nearestRailHub: 'New Jalpaiguri',
    nearestAirport: 'Bagdogra',
    bestMonths: ['March', 'April', 'May', 'October', 'November'],
    avoidMonths: ['July', 'August'],
    budgetHighlights: ['Toy train is a nice extra, not the budget core route.', 'Off-mall road hotels tend to be better value than central old properties.'],
    localTransportNote: 'Shared jeeps and walking are key; steep terrain makes frequent taxis expensive over multiple days.',
    sampleBudgetPerDay: 2100,
    sampleMidBudgetPerDay: 3500,
    tags: ['tea', 'mountains', 'east'],
    planningScore: 4.5,
  },
  {
    id: 'shillong',
    name: 'Shillong',
    region: 'Meghalaya',
    country: 'India',
    baseCostIndex: 1.0,
    description: 'Northeast city break that works best when based on shared cab access from Guwahati and day-trips kept structured.',
    avgHotelPrice: 2200,
    imageUrl: `${destinationImageBase}photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'northeast',
    zone: 'northeast',
    nearestRailHub: 'Guwahati',
    nearestAirport: 'Shillong / Guwahati',
    bestMonths: ['October', 'November', 'December', 'March', 'April'],
    avoidMonths: ['June', 'July', 'August'],
    budgetHighlights: ['Shared taxi access from Guwahati is the normal budget entry path.', 'Base in Shillong and avoid changing hotels for every day-trip.'],
    localTransportNote: 'Day-trips usually require cab coordination; grouping nearby stops matters more than room savings.',
    sampleBudgetPerDay: 2200,
    sampleMidBudgetPerDay: 3700,
    tags: ['northeast', 'waterfalls', 'roadtrip'],
    planningScore: 4.4,
  },
  {
    id: 'khajuraho',
    name: 'Khajuraho',
    region: 'Madhya Pradesh',
    country: 'India',
    baseCostIndex: 0.86,
    description: 'Compact heritage stop with moderate room prices, but better as a tightly planned short trip than an open-ended stay.',
    avgHotelPrice: 1800,
    imageUrl: `${destinationImageBase}photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'heritage_city',
    zone: 'central',
    nearestRailHub: 'Khajuraho',
    nearestAirport: 'Khajuraho',
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    avoidMonths: ['May', 'June'],
    budgetHighlights: ['One or two nights is usually enough, which keeps total spend lean.', 'Train access can be slower but often beats airfare on value.'],
    localTransportNote: 'The temple circuit is compact enough that local transport spend should stay low.',
    sampleBudgetPerDay: 1800,
    sampleMidBudgetPerDay: 3000,
    tags: ['heritage', 'architecture', 'short-trip'],
    planningScore: 4.2,
  },
  {
    id: 'orchha',
    name: 'Orchha',
    region: 'Madhya Pradesh',
    country: 'India',
    baseCostIndex: 0.74,
    description: 'Excellent low-cost heritage town with walkable sights and guesthouses that stay affordable year-round outside key holidays.',
    avgHotelPrice: 1400,
    imageUrl: `${destinationImageBase}photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'heritage_city',
    zone: 'central',
    nearestRailHub: 'Jhansi',
    nearestAirport: 'Gwalior',
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    avoidMonths: ['May', 'June'],
    budgetHighlights: ['Orchha is one of the best-value heritage overnights in North India.', 'Jhansi rail access keeps total transfer cost low.'],
    localTransportNote: 'Most main sights are walkable; autos are mainly for station connections and outlying cenotaph viewpoints.',
    sampleBudgetPerDay: 1500,
    sampleMidBudgetPerDay: 2500,
    tags: ['heritage', 'budget', 'slow-travel'],
    planningScore: 4.4,
  },
  {
    id: 'pushkar',
    name: 'Pushkar',
    region: 'Rajasthan',
    country: 'India',
    baseCostIndex: 0.88,
    description: 'Reliable low- to mid-budget desert-edge town with hostels, guesthouses, and easy pairing with Jaipur or Ajmer routes.',
    avgHotelPrice: 1800,
    imageUrl: `${destinationImageBase}photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'pilgrimage',
    zone: 'north',
    nearestRailHub: 'Ajmer',
    nearestAirport: 'Jaipur',
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    avoidMonths: ['May', 'June'],
    budgetHighlights: ['Ajmer rail plus short transfer is the standard budget path.', 'Prices move sharply during the Pushkar Camel Fair.'],
    localTransportNote: 'Town core is mostly walkable; local transport should be minimal unless adding nearby desert activities.',
    sampleBudgetPerDay: 1800,
    sampleMidBudgetPerDay: 3000,
    tags: ['spiritual', 'hostels', 'desert'],
    planningScore: 4.3,
  },
  {
    id: 'coorg',
    name: 'Coorg',
    region: 'Karnataka',
    country: 'India',
    baseCostIndex: 1.02,
    description: 'Coffee-country escape where budget success depends on bus arrival and carefully chosen homestays near your activity cluster.',
    avgHotelPrice: 2300,
    imageUrl: `${destinationImageBase}photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'hill_station',
    zone: 'south',
    nearestRailHub: 'Mysuru',
    nearestAirport: 'Mangaluru / Bengaluru',
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March'],
    avoidMonths: ['July'],
    budgetHighlights: ['Bus plus homestay works better than self-drive car rental on tight budgets.', 'Distances inside Coorg make location choice more important than room class.'],
    localTransportNote: 'Private taxis are expensive for scattered attractions, so plan by area instead of zig-zagging each day.',
    sampleBudgetPerDay: 2200,
    sampleMidBudgetPerDay: 3800,
    tags: ['coffee', 'nature', 'weekend'],
    planningScore: 4.4,
  },
  {
    id: 'mahabalipuram',
    name: 'Mahabalipuram',
    region: 'Tamil Nadu',
    country: 'India',
    baseCostIndex: 0.84,
    description: 'Easy heritage-and-coast short break from Chennai with manageable local costs and strong two-night value.',
    avgHotelPrice: 1700,
    imageUrl: `${destinationImageBase}photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80`,
    travelProfile: 'heritage_city',
    zone: 'south',
    nearestRailHub: 'Chengalpattu',
    nearestAirport: 'Chennai',
    bestMonths: ['November', 'December', 'January', 'February'],
    avoidMonths: ['May', 'June'],
    budgetHighlights: ['Direct buses from Chennai keep access cheap and simple.', 'A two-night stay is usually enough for core monuments and beach time.'],
    localTransportNote: 'Town is compact; walking and short auto rides are usually enough.',
    sampleBudgetPerDay: 1700,
    sampleMidBudgetPerDay: 2800,
    tags: ['unesco', 'coast', 'short-trip'],
    planningScore: 4.2,
  },
];

export const launchDeals: Deal[] = [
  {
    id: 'deal-shoulder-season',
    title: 'Shoulder Season Stay Strategy',
    description: 'Prioritize March-April or September-October for mountain and heritage routes to unlock better room rates without monsoon tradeoffs.',
    code: 'SHOULDERSMART',
    discountType: 'percentage',
    value: 12,
    eligibilityRule: 'Best fit for destinations where weather remains stable outside long-weekend peaks.',
    expiresAt: 'Launch season',
  },
  {
    id: 'deal-rail-first',
    title: 'Rail-First Budget Combo',
    description: 'On long corridors, overnight train plus central guesthouse usually beats budget flights once airport transfers are counted.',
    code: 'RAILFIRST',
    discountType: 'fixed',
    value: 1800,
    eligibilityRule: 'Works best for 3-night-plus itineraries where one overnight train saves a hotel night.',
    expiresAt: 'Launch season',
  },
  {
    id: 'deal-shared-transfer',
    title: 'Shared Transfer Saver',
    description: 'Hill stations and Northeast routes get materially cheaper when the final transfer is shared instead of private.',
    code: 'SHAREDRIDE',
    discountType: 'fixed',
    value: 1200,
    eligibilityRule: 'Applies to destinations where the railhead or airport is still 2 to 5 hours away.',
    expiresAt: 'Launch season',
  },
  {
    id: 'deal-two-night-city',
    title: 'Two-Night City Break Plan',
    description: 'For Jaipur, Mysuru, Amritsar, and Pondicherry, a tight two-night format often delivers the best cost-to-experience ratio.',
    code: 'TWONIGHT',
    discountType: 'fixed',
    value: 900,
    eligibilityRule: 'Ideal for compact city breaks with direct transport and walkable cores.',
    expiresAt: 'Launch season',
  },
];

const originZoneAliases: Record<TravelZone, string[]> = {
  north: ['delhi', 'gurgaon', 'gurugram', 'noida', 'chandigarh', 'amritsar', 'dehradun', 'lucknow', 'jaipur', 'agra'],
  west: ['mumbai', 'pune', 'ahmedabad', 'surat', 'vadodara', 'rajkot', 'nashik', 'goa'],
  south: ['bengaluru', 'bangalore', 'chennai', 'hyderabad', 'kochi', 'cochin', 'thiruvananthapuram', 'trivandrum', 'mysuru', 'coimbatore'],
  east: ['kolkata', 'bhubaneswar', 'patna', 'ranchi', 'siliguri'],
  central: ['bhopal', 'indore', 'nagpur', 'jhansi', 'gwalior', 'raipur'],
  northeast: ['guwahati', 'shillong', 'agartala', 'imphal', 'aizawl', 'gangtok'],
};

const adjacentZones: Record<TravelZone, TravelZone[]> = {
  north: ['central', 'west'],
  west: ['north', 'central', 'south'],
  south: ['west', 'central', 'east'],
  east: ['central', 'south', 'northeast'],
  central: ['north', 'west', 'south', 'east'],
  northeast: ['east'],
};

function getBudgetMultiplier(budgetLevel: BudgetLevel) {
  switch (budgetLevel) {
    case 'mid':
      return 1.25;
    case 'luxury':
      return 1.9;
    default:
      return 1;
  }
}

function inferOriginZone(origin: string): TravelZone | null {
  const normalizedOrigin = origin.trim().toLowerCase();

  for (const [zone, aliases] of Object.entries(originZoneAliases) as [TravelZone, string[]][]) {
    if (aliases.some((alias) => normalizedOrigin.includes(alias))) {
      return zone;
    }
  }

  return null;
}

function getDistanceBucket(originZone: TravelZone | null, destinationZone: TravelZone) {
  if (!originZone) {
    return 'unknown';
  }

  if (originZone === destinationZone) {
    return 'same';
  }

  if (adjacentZones[originZone].includes(destinationZone)) {
    return 'adjacent';
  }

  return 'far';
}

function route(type: TransportType, destination: LaunchDestination, provider: string, duration: number, estimatedCost: number, stops: number, notes: string[]) {
  return {
    id: `${destination.id}-${type}-${provider.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
    tripId: '',
    type,
    duration,
    estimatedCost,
    provider,
    metadata: {
      stops,
      notes,
      nearestRailHub: destination.nearestRailHub,
      nearestAirport: destination.nearestAirport,
    },
  } satisfies Route;
}

function buildSameZoneRoutes(origin: string, destination: LaunchDestination, travelers: number, budgetLevel: BudgetLevel) {
  const travelerFactor = Math.max(1, travelers);
  const budgetFactor = getBudgetMultiplier(budgetLevel);

  switch (destination.travelProfile) {
    case 'hill_station':
    case 'northeast':
      return [
        route('bus', destination, `${origin} Intercity Bus`, 540, Math.round(850 * destination.baseCostIndex * travelerFactor), 3, ['Usually cheapest when booked 1 to 2 weeks out.']),
        route('train', destination, `Rail to ${destination.nearestRailHub} + shared transfer`, 620, Math.round(1050 * destination.baseCostIndex * travelerFactor), 2, ['Best value if the last-mile transfer is shared.']),
        route('taxi', destination, 'Private transfer', 420, Math.round(3400 * destination.baseCostIndex * Math.max(1, travelerFactor / 2) * budgetFactor), 0, ['Convenience option; tends to be poor value for solo travelers.']),
      ];
    case 'beach':
      return [
        route('train', destination, `${destination.nearestRailHub} coastal rail`, 420, Math.round(900 * destination.baseCostIndex * travelerFactor), 2, ['Usually the cheapest comfortable option on this corridor.']),
        route('bus', destination, `${origin} sleeper coach`, 560, Math.round(950 * destination.baseCostIndex * travelerFactor), 1, ['Works best on overnight legs.']),
        route('taxi', destination, 'Direct cab transfer', 300, Math.round(3600 * destination.baseCostIndex * Math.max(1, travelerFactor / 2) * budgetFactor), 0, ['Good only when split across 3 to 4 travelers.']),
      ];
    default:
      return [
        route('train', destination, `${origin} rail connection`, 360, Math.round(780 * destination.baseCostIndex * travelerFactor), 1, ['Usually best price-performance for short and medium corridors.']),
        route('bus', destination, `${origin} state or sleeper bus`, 480, Math.round(720 * destination.baseCostIndex * travelerFactor), 2, ['Cheapest when you are flexible on departure time.']),
        route('taxi', destination, 'Point-to-point cab', 280, Math.round(3200 * destination.baseCostIndex * Math.max(1, travelerFactor / 2) * budgetFactor), 0, ['Most useful for groups or tight weekend timing.']),
      ];
  }
}

function buildFarRoutes(origin: string, destination: LaunchDestination, travelers: number, budgetLevel: BudgetLevel) {
  const travelerFactor = Math.max(1, travelers);
  const budgetFactor = getBudgetMultiplier(budgetLevel);

  return [
    route('train', destination, `Long-distance rail to ${destination.nearestRailHub}`, 1320, Math.round(1650 * destination.baseCostIndex * travelerFactor * 1.05), 4, ['Usually the cheapest far-corridor option if you can spend one night in transit.']),
    route('flight', destination, `Flight to ${destination.nearestAirport}`, 330, Math.round(5200 * destination.baseCostIndex * Math.max(1, travelerFactor * 0.9) * Math.max(1, budgetFactor * 0.92)), 1, ['Fastest option; only wins on value when train time is a real constraint.']),
    route('train', destination, `Rail + last-mile taxi via ${destination.nearestRailHub}`, 980, Math.round(2600 * destination.baseCostIndex * Math.max(1, travelerFactor * 0.9) * Math.max(1, budgetFactor * 0.95)), 2, ['Often a practical compromise on destinations with expensive airport transfers.']),
  ];
}

export function generateLaunchRoutes(origin: string, destination: LaunchDestination, travelers: number, budgetLevel: BudgetLevel): Route[] {
  const originZone = inferOriginZone(origin);
  const distanceBucket = getDistanceBucket(originZone, destination.zone);

  if (distanceBucket === 'far') {
    return buildFarRoutes(origin, destination, travelers, budgetLevel);
  }

  return buildSameZoneRoutes(origin, destination, travelers, budgetLevel);
}

